### ISSUE TITLE
Support Ollama

### ISSUE THREAD

**Issue by ch0ccyra1n** [micr0-dev/AltBot#3]
As an alternative to using Google's Gemini as a backend, it would be great to allow for someone deploying this amazing project to use Ollama as well. I might try to contribute code for this myself when I'm not as busy with my own projects.

**Comment by micr0-dev** [comment]
I already have code for this in another repo, I will work on making this code more deployable as in the state its really tuned for that one bot, and then also integrate ollama support

**Comment by ch0ccyra1n** [comment]
That's awesome to hear!

**Comment by micr0-dev** [comment]
Ollama is now supported!! :D 
https://fuzzies.wtf/@micr0/113196832155319406
