### ISSUE TITLE
feature-request: add "provided by altbot"

### ISSUE THREAD

**Issue by Schoeneh** [micr0-dev/AltBot#8]
Imo it would be great to add a line 'desc provided by altbot' to the end of the alt-text.
This woud make it easier to correctly attribute the alt-text.

Maybe like:
"Description provided by fuzzies.wtf/@altbot; generated using Gemini"

**Comment by micr0-dev** [comment]
im still thinking about this hmm

simultaneously it feels like it will be more cluttered, but also feels like it will be a good thing

**Comment by Schoeneh** [comment]
67 chars should be fine :)
You could even abbreviate &shorten to smth like "Desc. by https://fuzzies.wtf/@altbot" - only 36 chars

**Comment by micr0-dev** [comment]
okay one issue is that if i create this, I will need to translate it into every single language that i currently support, hmm

**Comment by Schoeneh** [comment]
Maybe as part of the prompt & let Gemini handle it?

**Comment by micr0-dev** [comment]
same issue still applies, each prompt is localized to a different language

**Comment by Schoeneh** [comment]
how many are we talling about?

**Comment by Schoeneh** [comment]
I could probably provide (via people I know) translations for all of the European languages (including Belorussian and Russian)

**Comment by micr0-dev** [comment]
hmmm, I feel like we should get more opinions, I'll make a poll on fedi

**Comment by austinhuang0131** [comment]
would it be more appropriate to bypass character limit by hosting a barebone activitypub server with the bot tho

**Comment by micr0-dev** [comment]
> would it be more appropriate to bypass character limit by hosting a barebone activitypub server with the bot tho

there already is not a character limit on fuzzies.wtf

**Comment by rkingett** [comment]
I’m a screen reader user, and I’m struggling to see how this could ease up on screen reader and display redundancy. because I’m primarily reading things on a Braille display or hearing it through a screen reader and it seems like the text is redundant because I can look and see the display name of the bot as well as the username of the bot. If you mean for users that copy and paste the image/media descriptions added later, that disclaimer would be very helpful in transparency

**Comment by Schoeneh** [comment]
> If you mean for users that copy and paste the image/media descriptions added later, that disclaimer would be very helpful in transparency

Exactly this is my use case & why I opened this issue :)
